"""
UniControl - Report Model
=========================
Report model for generating and storing reports.

Author: UniControl Team
Version: 1.0.0
"""

from datetime import datetime, date
from enum import Enum
from typing import Optional, TYPE_CHECKING
from sqlalchemy import String, Integer, DateTime, Date, ForeignKey, Text, Boolean, Enum as SAEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.config import TASHKENT_TZ
from app.database import Base

if TYPE_CHECKING:
    from app.models.user import User
    from app.models.group import Group


class ReportType(str, Enum):
    """Report type enum."""
    ATTENDANCE = "attendance"
    PAYMENT = "payment"
    STUDENTS = "students"
    GROUPS = "groups"
    ANALYTICS = "analytics"
    AI_ANALYSIS = "ai_analysis"
    CUSTOM = "custom"


class ReportFormat(str, Enum):
    """Report format enum."""
    PDF = "pdf"
    EXCEL = "excel"
    CSV = "csv"
    JSON = "json"


class ReportStatus(str, Enum):
    """Report status enum."""
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    APPROVED = "approved"
    REJECTED = "rejected"


class Report(Base):
    """
    Report model.
    
    Manages generated reports.
    """
    
    __tablename__ = "reports"
    
    # Primary key
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    
    # Report info
    name: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        comment="Report name"
    )
    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Report description"
    )
    
    # Type and format
    report_type: Mapped[ReportType] = mapped_column(
        SAEnum(ReportType),
        nullable=False,
        index=True,
        comment="Report type"
    )
    format: Mapped[ReportFormat] = mapped_column(
        SAEnum(ReportFormat),
        nullable=False,
        default=ReportFormat.EXCEL,
        comment="Report format"
    )
    
    # Status
    status: Mapped[ReportStatus] = mapped_column(
        SAEnum(ReportStatus),
        nullable=False,
        default=ReportStatus.PENDING,
        index=True,
        comment="Report status"
    )
    
    # Date range
    date_from: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        comment="Start date"
    )
    date_to: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        comment="End date"
    )
    
    # Filters
    group_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("groups.id", ondelete="SET NULL"),
        nullable=True,
        comment="Filter by group"
    )
    filters: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Additional filters as JSON"
    )
    
    # Generated by
    created_by: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=False,
        comment="User who generated report"
    )
    
    # File info
    file_path: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Generated file path"
    )
    file_size: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="File size in bytes"
    )
    download_url: Mapped[Optional[str]] = mapped_column(
        String(500),
        nullable=True,
        comment="Download URL"
    )
    
    # Processing info
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Processing start time"
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Processing completion time"
    )
    error_message: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Error message if failed"
    )
    
    # AI Analysis fields
    ai_prompt: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="AI analysis prompt"
    )
    ai_result: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="AI analysis result"
    )
    ai_model: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
        comment="AI model used"
    )
    ai_tokens_used: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
        comment="AI tokens used"
    )
    
    # Download count
    download_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Number of downloads"
    )
    
    # Approval fields
    approved_by: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User who approved/rejected the report"
    )
    approved_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="Approval/rejection time"
    )
    rejection_reason: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        comment="Reason for rejection"
    )
    
    # Expiry
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        comment="File expiry time"
    )
    
    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(TASHKENT_TZ),
        nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(TASHKENT_TZ),
        onupdate=lambda: datetime.now(TASHKENT_TZ),
        nullable=False
    )
    
    # Relationships
    created_by_user: Mapped["User"] = relationship(
        "User",
        foreign_keys=[created_by],
        lazy="joined"
    )
    
    approved_by_user: Mapped[Optional["User"]] = relationship(
        "User",
        foreign_keys=[approved_by],
        lazy="joined"
    )
    
    group: Mapped[Optional["Group"]] = relationship(
        "Group",
        foreign_keys=[group_id],
        lazy="joined"
    )
    
    def __repr__(self) -> str:
        return f"<Report(id={self.id}, name='{self.name}', type={self.report_type.value})>"
    
    @property
    def is_pending(self) -> bool:
        """Check if report is pending."""
        return self.status == ReportStatus.PENDING
    
    @property
    def is_processing(self) -> bool:
        """Check if report is processing."""
        return self.status == ReportStatus.PROCESSING
    
    @property
    def is_completed(self) -> bool:
        """Check if report is completed."""
        return self.status == ReportStatus.COMPLETED
    
    @property
    def is_failed(self) -> bool:
        """Check if report failed."""
        return self.status == ReportStatus.FAILED
    
    @property
    def is_approved(self) -> bool:
        """Check if report is approved."""
        return self.status == ReportStatus.APPROVED
    
    @property
    def is_rejected(self) -> bool:
        """Check if report is rejected."""
        return self.status == ReportStatus.REJECTED
    
    @property
    def processing_time(self) -> Optional[float]:
        """Get processing time in seconds."""
        if self.started_at and self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return None
    
    @property
    def is_expired(self) -> bool:
        """Check if report file is expired."""
        if self.expires_at is None:
            return False
        return datetime.now(TASHKENT_TZ) > self.expires_at
