"""Add clubs, subjects, directions, tournaments tables

Revision ID: 0e185a7fabdd
Revises: 001_initial
Create Date: 2026-01-29 15:28:38.996844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e185a7fabdd'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_members'))
    )
    op.create_index(op.f('ix_club_members_club_id'), 'club_members', ['club_id'], unique=False)
    op.create_index(op.f('ix_club_members_id'), 'club_members', ['id'], unique=False)
    op.create_index(op.f('ix_club_members_student_id'), 'club_members', ['student_id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('teacher', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('members_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('direction_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direction_subjects'))
    )
    op.create_index(op.f('ix_direction_subjects_direction_id'), 'direction_subjects', ['direction_id'], unique=False)
    op.create_index(op.f('ix_direction_subjects_id'), 'direction_subjects', ['id'], unique=False)
    op.create_index(op.f('ix_direction_subjects_subject_id'), 'direction_subjects', ['subject_id'], unique=False)
    op.create_table('directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directions')),
    sa.UniqueConstraint('code', name=op.f('uq_directions_code'))
    )
    op.create_index(op.f('ix_directions_id'), 'directions', ['id'], unique=False)
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Kategoriya nomi'),
    sa.Column('description', sa.Text(), nullable=True, comment='Kategoriya tavsifi'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Icon nomi'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='Rang kodi'),
    sa.Column('sort_order', sa.Integer(), nullable=True, comment='Tartib raqami'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Faollik holati'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_categories'))
    )
    op.create_index(op.f('ix_menu_categories_id'), 'menu_categories', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('hours_per_week', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('code', name=op.f('uq_subjects_code'))
    )
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('tournament_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_registrations'))
    )
    op.create_index(op.f('ix_tournament_registrations_id'), 'tournament_registrations', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_registrations_student_id'), 'tournament_registrations', ['student_id'], unique=False)
    op.create_index(op.f('ix_tournament_registrations_tournament_id'), 'tournament_registrations', ['tournament_id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('prize', sa.String(length=500), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments'))
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('canteen_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.String(length=20), nullable=False, comment='Buyurtma raqami'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Foydalanuvchi ID'),
    sa.Column('status', sa.Enum('PENDING', 'PREPARING', 'READY', 'COMPLETED', 'CANCELLED', name='orderstatus'), nullable=False, comment='Buyurtma holati'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Jami summa'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Izohlar'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Yaratilgan vaqt'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Bajarilgan vaqt'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_canteen_orders_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canteen_orders')),
    sa.UniqueConstraint('order_number', name=op.f('uq_canteen_orders_order_number'))
    )
    op.create_index(op.f('ix_canteen_orders_id'), 'canteen_orders', ['id'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Kategoriya ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Taom nomi'),
    sa.Column('description', sa.Text(), nullable=True, comment='Tavsif'),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False, comment="Narxi (so'm)"),
    sa.Column('image_url', sa.String(length=500), nullable=True, comment='Rasm URL'),
    sa.Column('is_available', sa.Boolean(), nullable=True, comment='Mavjudlik'),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True, comment='Vegetarian'),
    sa.Column('is_halal', sa.Boolean(), nullable=True, comment='Halol'),
    sa.Column('calories', sa.Integer(), nullable=True, comment='Kaloriya'),
    sa.Column('preparation_time', sa.Integer(), nullable=True, comment='Tayyorlanish vaqti (daqiqa)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], name=op.f('fk_menu_items_category_id_menu_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_items'))
    )
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_table('canteen_order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False, comment='Buyurtma ID'),
    sa.Column('menu_item_id', sa.Integer(), nullable=True, comment='Menyu elementi ID'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Miqdor'),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Birlik narxi'),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False, comment='Jami narxi'),
    sa.Column('item_name', sa.String(length=200), nullable=False, comment='Taom nomi (snapshot)'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name=op.f('fk_canteen_order_items_menu_item_id_menu_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['canteen_orders.id'], name=op.f('fk_canteen_order_items_order_id_canteen_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_canteen_order_items'))
    )
    op.create_index(op.f('ix_canteen_order_items_id'), 'canteen_order_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canteen_order_items_id'), table_name='canteen_order_items')
    op.drop_table('canteen_order_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_canteen_orders_id'), table_name='canteen_orders')
    op.drop_table('canteen_orders')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_tournament_registrations_tournament_id'), table_name='tournament_registrations')
    op.drop_index(op.f('ix_tournament_registrations_student_id'), table_name='tournament_registrations')
    op.drop_index(op.f('ix_tournament_registrations_id'), table_name='tournament_registrations')
    op.drop_table('tournament_registrations')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_menu_categories_id'), table_name='menu_categories')
    op.drop_table('menu_categories')
    op.drop_index(op.f('ix_directions_id'), table_name='directions')
    op.drop_table('directions')
    op.drop_index(op.f('ix_direction_subjects_subject_id'), table_name='direction_subjects')
    op.drop_index(op.f('ix_direction_subjects_id'), table_name='direction_subjects')
    op.drop_index(op.f('ix_direction_subjects_direction_id'), table_name='direction_subjects')
    op.drop_table('direction_subjects')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_club_members_student_id'), table_name='club_members')
    op.drop_index(op.f('ix_club_members_id'), table_name='club_members')
    op.drop_index(op.f('ix_club_members_club_id'), table_name='club_members')
    op.drop_table('club_members')
    # ### end Alembic commands ###
